### ISSUE TITLE
Integrating X-LoRA

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/peft#1472]
Hello all, and thank you for your great work!

Earlier this week, we announced [X-LoRA](https://arxiv.org/abs/2402.07148), a flexible MoE approach for LoRA adapters. We implement deep layer- and token-wise scalings for multiple LoRA adapters and provide an implementation (https://github.com/EricLBuehler/xlora) that enables straightforward application to any model to which `peft` LoRA adapters may be applied to. This offers the possibility to orchestrate at a much finer level, that is, to achieve new combinations of adapter layers. This results in never-before-seen per-token deep layer-wise combinations of parameters to solve specific tasks. Sample weights are provided at: https://huggingface.co/lamm-mit/x-lora with examples in protein science in the paper. 

Would you be interested to perhaps integrate X-LoRA into `peft`? I would be happy to work on this if there is interest from you and the community.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this to our attention, this could be an interesting addition. I just had a quick glance at the repo but it looks quite solid to me.

I think something we should pay attention to if we want to integrate it to PEFT is the API. Ideally, we would like to be able to initiate an X-LoRA model (or load a trained one) just based on a config using the usual PEFT/transformers methods. That way, we could ensure that users can make use of X-LoRA without running custom code. I'm not sure how feasible that is, but it would be great to have.

**Comment by EricLBuehler** [comment]
I think this would be feasible. The primary entry point for converting to X-LoRA is a function `add_xlora_to_model`. It already takes a `PreTrainedModel` and we have a config class that could easily be ported. Specifically, would adding a new model type class where I would port the mechanics from `add_xlora_to_model` to the mapping make sense?

**Comment by BenjaminBossan** [comment]
> would adding a new model type class where I would port the mechanics from `add_xlora_to_model` to the mapping make sense?

Do you mean a new model class on the level of `PeftModel`, or something on the level of `LoraModel`? If the latter, yes, I think that would be a good idea here. Maybe you could just start with a quick draft PR and we see from there? Often it's easier to discuss once we can see the code.

**Comment by EricLBuehler** [comment]
I have an implementation that is nearly ready for a draft PR on my fork. However, after looking at how `PeftModel` initializes its base model, I think a modification to the instantiation call for the `PeftModel` base model may be necessary for `xLoRAModel` to be on the same level as `LoraModel`.

This is because in the `xlora` library we create a `PeftModel` which needs to be modified based on the `xLoRAConfig` (loading adapters, injecting methods and hooks, etc.). For example, we override the `save_pretrained` method to save adapters and the classifier in specific locations.

Perhaps one solution is to pass a reference to the `PeftModel` when creating the `xLoRAModel`? This way, the necessary methods can be overridden, and the `xLoRAModel` would be on the same level as `LoraModel`. Do you think that this method of passing a reference would be a good idea, or is there another way?

**Comment by BenjaminBossan** [comment]
It would be much easier to discuss possible solutions once I see how the code looks like :)

**Comment by EricLBuehler** [comment]
Ok, sounds good! I will submit a draft PR after I complete some small testing.

**Comment by A11en0** [comment]
It appears that the inference process is very slow when using four LoRA experts. In fact, it is significantly slower than four times the single LoRA inference time. Could you please explain why for me, thanks very much!

**Comment by BenjaminBossan** [comment]
@A11en0 Thanks for trying this out so quickly after it was merged :)

Do you have some code to replicate the issue? What times did you measure?

**Comment by A11en0** [comment]
When utilizing Xlora with four experts, processing 2000 samples—each averaging 500 in length—requires approximately 10 hours.

**Comment by A11en0** [comment]
```yaml
### model
model_name_or_path: Mistral-7B-Instruct-v0.2

### method
stage: sft
do_train: true
finetuning_type: xlora
lora_rank: 32
lora_alpha: 32
lora_target: q_proj,k_proj,v_proj,o_proj
saved_lora_adapters: project/outputs/lora_DI,project/outputs/lora_ED,project/outputs/lora_EM,project/outputs/lora_SM
use_trainable_adapters: false

### dataset
dataset: jellyfish
template: jellyfish
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/xlora
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 6.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_total_limit: 10
load_best_model_at_end: true

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500

## wandb
report_to: wandb
```

above is my yaml configure file.
