### ISSUE TITLE
Memory usage spike when using `merge_and_unload`

### ISSUE THREAD

**Issue by snarayan21** [huggingface/peft#1939]
### System Info

peft version 0.23.4
transformers version 4.42.3

### Who can help?

@BenjaminBossan @sayakpaul

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
model = model.merge_and_unload()
```

### Expected behavior

Hi, I'm trying to merge lora adapters into the model with the `merge_and_unload` function. My model is on `cpu`. I'm near the cpu memory limit on my machine so I would like the `merge_and_unload` operation to happen in-place, but there seems to be a spike in memory usage when this function is called, causing cpu OOM. Is there an in-place version of this function / what makes `merge_and_unload` increase cpu memory usage significantly?

**Comment by BenjaminBossan** [comment]
Do you have the error message? Could you also share the PEFT config and what base model you use?

**Comment by snarayan21** [comment]
Hey @BenjaminBossan, there's no error message per se because it's a CPU oom -- the job just crashes. I'm using `meta-llama/Meta-Llama-3-70B` with the peft config below:
```
peft_config:
      r: 16
      peft_type: LORA
      task_type: CAUSAL_LM
      lora_alpha: 32
      lora_dropout: 0
      target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
      - down_proj
      - up_proj
      - gate_proj
```

Looking at `_unload_and_optionally_merge`, is the LoRAModel holding on to additional unmerged parameters that it shouldn't be during the merge process?
