### ISSUE TITLE
PEFT QLoRA with DeepSpeed ZeRO3 on multiple GPUs not working as in documentation 

### ISSUE THREAD

**Issue by echo-yi** [huggingface/peft#1972]
### System Info

Hi, I'm following [this guide](https://huggingface.co/docs/peft/main/en/accelerate/deepspeed#use-peft-qlora-and-deepspeed-with-zero3-for-finetuning-large-models-on-multiple-gpus) to finetune Llama 3.1 405B, but ZeRO-3 doesn't seem to be enabled. 
When I run the command below, I get this log while loading the pretrained model, which indicates ZeRO-3 is not initialized. 
```
The device_map was not initialized. Setting device_map to {'':torch.cuda.current_device()}. If you want to use the model for inference, please set device_map ='auto' 
`low_cpu_mem_usage` was None, now set to True since model is quantized.
```
If I change ZeRO stage from 3 to 2, I don't get the log above. 
According to the guide, ZeRO-3 with QLoRA (bitsandbytes quantization) should work together, but as far as I tried, only ZeRO-2 with QLoRA is working, not ZeRO-3. 
Any help would be appreciated to enable ZeRO-3 with QLoRA. 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

**pretrained.py** 
```python
...
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    # bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.bfloat16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
...
```

**zero3_config.yaml**
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**command**
`accelerate launch --config_file zero3_config.yaml pretrain.py `
To be precise, I'm running this command with kubeflow, so 
```python
@dsl.container_component
def pretrain():
    return dsl.ContainerSpec(
        image='IMAGE_PATH',
        command=['accelerate', 'launch', '--config_file', 'zero3_config.yaml', 'pretrain.py'])

@dsl.pipeline(name=PIPELINE_NAME,
              description="pretrain",
              pipeline_root=PIPELINE_ROOT,
              )
def pipeline_func(
):
    train_task = pretrain()
    train_task.set_accelerator_type("nvidia.com/gpu")
    train_task.set_accelerator_limit(8)
```

**versions**
```python
# bitsandbytes>=0.43.0, accelerate>=0.28.0, transformers>4.38.2, trl>0.7.11 and peft>0.9.0
import bitsandbytes
import accelerate
import transformers
import trl
import peft
print(f'bitsandbytes=={bitsandbytes.__version__}') # 0.43.2
print(f'accelerate=={accelerate.__version__}') # 0.33.0
print(f'transformers=={transformers.__version__}') # 4.43.2
print(f'trl=={trl.__version__}') # 0.9.6
print(f'peft=={peft.__version__}') # 0.11.1
```

### Expected behavior

PEFT QLoRA with DeepSpeed ZeRO3 on multiple GPUs
