### ISSUE TITLE
DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

### ISSUE THREAD

**Issue by rafael-ariascalles** [huggingface/peft#306]
I am trying to train a flan-t5-xxl model using "INT8 training of large models in Colab using PEFT LoRA and bits_and_bytes" but using multiple GPUs  DeepSpeed and Accelerate

I am cinstantiate the model as:
```python
model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name_or_path,
    load_in_8bit=True,
    device_map={'': 0},
    torch_dtype=torch.float16
)
```

but I get the following error:
```
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.
[13:55:22] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 5364) of binary: /opt/conda/envs/pytorch/bin/python3.9   
```

the deepspeed config:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp8
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

any advice @pacman100 

I was follow the advice in the thread https://github.com/huggingface/peft/issues/93#issuecomment-1434080330
to add decive_map
